apiVersion: servers.cnc.demo/v1beta1
kind: WebManager
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: webmanager-demo3
spec:
  webSets: 5 
  intervalMillis: 2000
  autoDelete: False
  waitForFarewellMillis: 60000
  webServer:
    replicas: 2
    content: Hello, WebManager 3 !
    port:
      http: 8080
