
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: webservers.servers.cnc.demo
spec:
  group: servers.cnc.demo
  names:
    kind: WebServer
    plural: webservers
  scope: ""
  validation:
    openAPIV3Schema:
      description: WebServer is the Schema for the webservers API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: WebServerSpec defines the desired state of WebServer
          properties:
            content:
              type: string
            port:
              properties:
                http:
                  format: int32
                  type: integer
              type: object
            replicas:
              format: int32
              type: integer
          type: object
        status:
          description: WebServerStatus defines the observed state of WebServer
          type: object
      type: object
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
